. "$HOME/.cargo/env"
export HISTSIZE=2000
export DIRSTACKSIZE=20
export SAVEHIST=2000
export KEYTIMEOUT=1
export HISTFILE=~/.cache/zsh/zsh_history
export VISUAL='/usr/bin/nvim'
export EDITOR='/usr/bin/nvim'
export BROWSER='brave'
export ZDOTDIR=~/.config/zsh/
